#
#             Spectate v1.0
#   	      Автор: Тимур
#   	   Телеграм: @tmrtrsvch
#
# /spec <игрок> (spectate.use) - Начать вести наблюдение за игроком
# /unspec <игрок> (spectate.use) - Прекратить вести наблюдение за игроком
#

messages:
  no_permission: "&#7A00FFНаблюдение&7&l: &fУ Вас нет прав для выполнения данной команды"
  player_not_found: "&#7A00FFНаблюдение&7&l: &fДанный игрок не найден"
  cannot_spectate_yourself: "&#7A00FFНаблюдение&7&l: &fВы не можете наблюдать за самим собой"
  not_spectating: "&#7A00FFНаблюдение&7&l: &fВы не ведёте ни за кем наблюдение"
  start_spectating: "&#7A00FFНаблюдение&7&l: &fВы начали вести наблюдение за игроком &#7A00FF%player%"
  stop_spectating: "&#7A00FFНаблюдение&7&l: &fВы прекратили вести наблюдение за игроком"

  spectate_usage:
    - ""
    - "  &fНачать вести наблюдение за игроком &7» &#7A00FF/spec <игрок>"
    - "  &fПерестать вести наблюдение за игроком &7» &#7A00FF/unspec"
    - ""

  only_for_players: "&cЭта команда доступна только для игроков"